apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ossci-test-pvc
  namespace: ossci-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: ossci-test
