apiVersion: v1
kind: Pod
metadata:
  name: {{POD_NAME}}
spec:
  nodeSelector:
    kubernetes.io/hostname: chi-mi325x-pod2-026
  tolerations:
    - key: "demo"
      operator: "Equal"
      value: "yes"
      effect: "NoSchedule"
  volumes:
    - name: home-vol
      persistentVolumeClaim:
        claimName: {{PVC_CLAIM_NAME}}
    - name: ssh-key
      secret:
        secretName: vscode-ssh-key
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  containers:
    - name: vscode-ssh
      image: ghcr.io/nod-ai/ossci-gitops/rocm-dev:ossci-test@sha256:af655ad69c46c7af76db58c597d82d277c4f71d1343b2867c85b2bc77a66ca6a
      command:
        - /bin/bash
        - -c
        - |
          set -eux
          sudo apt-get update && sudo apt-get install -y sudo openssh-server curl vim

          # Ensure proper ownership
          sudo chown -R ossci:ossci /home/ossci

          # Setup SSH access
          mkdir -p /home/ossci/.ssh
          cp /mnt/sshkey/authorized_keys /home/ossci/.ssh/authorized_keys
          chmod 700 /home/ossci/.ssh
          chmod 600 /home/ossci/.ssh/authorized_keys

          # Start SSH daemon
          sudo mkdir -p /var/run/sshd
          sudo /usr/sbin/sshd -D
      volumeMounts:
        - name: home-vol
          mountPath: /home/ossci
          readOnly: false
        - name: ssh-key
          mountPath: /mnt/sshkey
          readOnly: true
      resources:
        limits:
          amd.com/gpu: 1
