apiVersion: v1
kind: Pod
metadata:
  name: {{POD_NAME}}
spec:
  volumes:
    - name: home-vol
      persistentVolumeClaim:
        claimName: {{PVC_CLAIM_NAME}}
    - name: ssh-key
      secret:
        secretName: ssh-key-{{POD_NAME}}
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: {{DEV_GID}}
    fsGroupChangePolicy: OnRootMismatch
  containers:
    - name: vscode-ssh
      image: {{IMAGE}}
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: home-vol
          mountPath: {{HOME_DIR}}
          readOnly: false
        - name: ssh-key
          mountPath: /mnt/sshkey
          readOnly: true
      resources:
        limits:
          amd.com/gpu: {{GPU_LIMIT}}
