apiVersion: v1
kind: Pod
metadata:
  name: {{POD_NAME}}
spec:
  nodeSelector:
    kubernetes.io/hostname: chi-mi325x-pod2-026
  tolerations:
    - key: "demo"
      operator: "Equal"
      value: "yes"
      effect: "NoSchedule"
  volumes:
    - name: home-vol
      persistentVolumeClaim:
        claimName: {{PVC_CLAIM_NAME}}
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  containers:
    - name: vscode-web
      image: ghcr.io/nod-ai/ossci-gitops/rocm-dev:ossci-test@sha256:af655ad69c46c7af76db58c597d82d277c4f71d1343b2867c85b2bc77a66ca6a
      command:
        - /bin/bash
        - -c
        - |
          set -eux
          sudo apt-get update && sudo apt-get install -y curl
          sudo chown -R ossci:ossci /home/ossci
          curl -fsSL https://code-server.dev/install.sh | sh
          code-server --auth none --port 9000
      tty: true
      stdin: true
      volumeMounts:
        - name: home-vol
          mountPath: /home/ossci
          readOnly: false
      resources:
        limits:
          amd.com/gpu: 1
